spring:
  application:
    name: dubbo-provider
dubbo:
  application:
    name: provider-demo
    id: provider-demo
  registry:
    address: zookeeper://10.1.11.147:2888
  scan:
    base-packages: com.example.dubbo.provider.service.dubbo.impl
  protocol:
    name: dubbo
    port: 12345
    accesslog: true

logging:
  config: C:\projects\demo\learn\logback.xml

num: 1