spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:p6spy:mysql://rm-2ze72az7l7200xb22.mysql.rds.aliyuncs.com:3306/urumqi_order"
    username: "dev_read"
    password: "8QilAfoCL3doriob"

logging:
  level:
    com.example.mybatisplus.dao: debug
