version: "3"
services:
  nacos:
    image: nacos/nacos-server:v2.2.3-slim
    container_name: nacos-server
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_DATABASE_NUM=1
      - MYSQL_SERVICE_HOST=host.docker.internal
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=rootroot
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    volumes:
      - /Users/yang/home/opt/docker/nacos/data:/home/nacos/data
      - /Users/yang/home/opt/docker/nacos/logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
