version: "3"
services:
  nginx:
    image: arm64v8/nginx:1.22.1
    container_name: nginx
    volumes:
      - /Users/yang/home/opt/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /Users/yang/home/opt/docker/nginx/conf/conf.d:/etc/nginx/conf.d
      - /Users/yang/home/opt/docker/nginx/log:/var/log/nginx
      - /Users/yang/home/opt/docker/nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"
