version: "3"
services:
  redis:
    image: arm64v8/redis:6.0.20
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - /Users/yang/home/opt/docker/redis/redis.conf:/etc/redis/redis.conf
      - /Users/yang/home/opt/docker/redis/data:/data
    ports:
      - "6379:6379"
