version: '3'
services:
  namesrv:
    image: apache/rocketmq:5.1.4
    container_name: namesrv
    command: sh mqnamesrv
    ports:
      - "9876:9876"
    volumes:
      - /Users/yang/home/opt/docker/rocketmq/namesrvlogs:/root/logs
      - /Users/yang/home/opt/docker/rocketmq/namesrv:/root/store
    networks:
      - rocketmq-network
  broker1:
    image: apache/rocketmq:5.1.4
    container_name: rmqbroker1
    command: sh mqbroker -n namesrv:9876
    ports:
      - "10911:10911"
      - "10909:10909"
    environment:
      - "JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    volumes:
      - /Users/yang/home/opt/docker/rocketmq/broker1logs:/root/logs
      - /Users/yang/home/opt/docker/rocketmq/broker1:/root/store
    depends_on:
      - namesrv
    networks:
      - rocketmq-network
  broker2:
    image: apache/rocketmq:5.1.4
    container_name: rmqbroker2
    command: sh mqbroker -n namesrv:9876
    ports:
      - "11911:11911"
      - "11909:11909"
    environment:
      - "JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    volumes:
      - /Users/yang/home/opt/docker/rocketmq/broker2logs:/root/logs
      - /Users/yang/home/opt/docker/rocketmq/broker2:/root/store
    depends_on:
      - namesrv
    networks:
      - rocketmq-network
  broker3:
    image: apache/rocketmq:5.1.4
    container_name: rmqbroker3
    command: sh mqbroker -n namesrv:9876
    ports:
      - "12911:12911"
      - "12909:12909"
    environment:
      - "JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    volumes:
      - /Users/yang/home/opt/docker/rocketmq/broker3logs:/root/logs
      - /Users/yang/home/opt/docker/rocketmq/broker3:/root/store
    depends_on:
      - namesrv
    networks:
      - rocketmq-network


  rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:1.0.0
    volumes:
      - /Users/yang/home/opt/docker/rocketmq/dashboard/tmp:/tmp
    ports:
      - "8080:8080"
    environment:
      - NAMESRV_ADDR=namesrv:9876
    networks:
      - rocketmq-network
networks:
  rocketmq-network: