
spring:
  application:
    name: dubbo-consumer

dubbo:
  application:
    name: consumer-demo
    id: consumer-demo
  registry:
    address: zookeeper://10.1.11.147:2888
  consumer:
    check: false
    timeout: 100000
    retries: 0
    filter: -myFilter
logging:
  config: C:\projects\demo\learn\logback.xml