spring:
  profiles:
    active: prod,test,dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 3000
      use-unfair-lock: true
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      use-global-data-source-stat: true
      web-stat-filter:
        enabled: true
        url-pattern: /druid/*
      stat-view-servlet:
        enabled: true
        reset-enable: false
        login-username: admin
        login-password: admin
  kafka:
    bootstrap-servers:
      - 10.1.11.147:9092
    consumer:
      group-id: learn
    listener:
      missing-topics-fatal: false
management:
  endpoints:
    web:
      exposure:
        include: "*"


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mybatis.domain

#my:
#  yaml:
#    file:
#      path: ss/ssd/sdsd.yaml
test:
  constructor: false
  user:
    id: 12
    name: asdf
    sex: 1
jwt:
  token:
    secret: Hsvg9jZbN

exclude:
  list: "/asdf,/asdfs,/user"

value: ssss
