server:
  port: 8080
spring:
  redis:
    host: 10.1.11.110
    port: 6390
    password: "6390"
    database: 8
    jedis:
      pool:
        max-active: 8
        min-idle: 5
        max-idle: 8
        max-wait: PT15M
        time-between-eviction-runs: PT15M
  datasource:
    password: ByrDKbceYvZENads
    username: baojia-db-3
    url: jdbc:mysql://10.1.11.110:3306/baojia_box?&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource


