server:
  port: 8081

spring:
  redis:
    host: 10.1.11.110
    port: 6390
    password: "6390"
    jedis:
      pool:
        max-active: 8
        min-idle: 5
        max-idle: 8
        max-wait: PT15M
#    lettuce:
#      pool:
#        max-active: 7
#        min-idle: 2
#        max-idle: 5
#        max-wait: PT15M


